config/routes.rb
Rails.application.routes.draw do
  resources :elves
  resources :presents
  resources :dashboards
 
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/elf.rb
class Elf < ApplicationRecord
  has_many :presents
  #== Constants ================================================================
  #== Attributes ===============================================================
  #== Extensions ===============================================================
  #== Relationships ============================================================
  #== Validations ==============================================================
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :speciality
  #== Scopes ===================================================================
  #== Callbacks ================================================================
  #== Class Methods ============================================================
  #== Instance Methods =========================================================
end

app/models/present.rb
class Present < ApplicationRecord
  belongs_to :elf
  #== Constants ================================================================
  #== Attributes ===============================================================
  #== Extensions ===============================================================
  #== Relationships ============================================================
  #== Validations ==============================================================
  validates_presence_of :contents
  validates_presence_of :name_recepient
  validates_presence_of :elf_id
  validates_presence_of :status
  #== Scopes ===================================================================
  #== Callbacks ================================================================
  #== Class Methods ============================================================
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  include LogragePayload
  include ActiveModelSerializerPagination

  self.responder = ApplicationResponder
  respond_to :html
end

app/controllers/concerns/active_model_serializer_pagination.rb
module ActiveModelSerializerPagination
  extend ActiveSupport::Concern

  def pagination_meta(object)
    {
      current_page: object.current_page,
      next_page:    object.next_page,
      prev_page:    object.prev_page,
      total_pages:  object.total_pages,
      total_count:  object.total_count
    }
  end
end

app/controllers/concerns/lograge_payload.rb
module LogragePayload
  extend ActiveSupport::Concern

  def append_info_to_payload(payload)
    super
    payload[:request_id] = request.uuid
    payload[:user_id] = current_user.id if try(:current_user)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  respond_to :html
  def index
  	@q = Elf.all.search params[:q]
    @elves = @q.result.page(params[:page])
    #respond_with @elves, meta: pagination_meta(@elves)

    #Also add presents to the controller
  	@q = Present.all.search params[:q]
    @presents = @q.result.page(params[:page])

    respond_with @presents, meta: pagination_meta(@presents)

  end
end

app/controllers/elves_controller.rb
class ElvesController < ApplicationController
  respond_to :html

  def index
    @q = Elf.all.search params[:q]
    @elves = @q.result.page(params[:page])
    respond_with @elves, meta: pagination_meta(@elves)
  end

  def show
    @elf = Elf.find params[:id]
    respond_with @elf
  end

  def new
    @elf = Elf.new
  end

  def edit
    @elf = Elf.find params[:id]
    respond_with @elf
  end

  def create
    @elf = Elf.new(elf_params)
    @elf.save
    respond_with @elf
  end

  def update
    @elf = Elf.find params[:id]
    @elf.update(elf_params)
    respond_with @elf
  end

  def destroy
    @elf = Elf.find params[:id]
    @elf.destroy
    respond_with @elf
  end

  private

  def elf_params
    params.require(:elf).permit(
      :first_name,
      :last_name,
      :date_of_birth,
      :speciality
    )
  end

 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  def index
  end
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  respond_to :html

  def index
    @q = Present.all.search params[:q]
    @presents = @q.result.page(params[:page])

    respond_with @presents, meta: pagination_meta(@presents)
  end

  def show
    @present = Present.find params[:id]
    respond_with @present
  end

  def new
    if(params[:contents] && params[:name_recepient])
        @present = Present.find(params[:present_contents, :name_recepient, :elf_id])
        @inspiration = Inspiration.find(params[:inspiration_id])
    else
      @present = Present.new
    end
  end

  def edit
    @present = Present.find params[:id]
    respond_with @present
  end

  def create
    @present = Present.new(present_params)
    @present.save
    respond_with @present
  end

  def update
    @present = Present.find params[:id]
    @present.update(present_params)
    respond_with @present
  end

  def destroy
    @present = Present.find params[:id]
    @present.destroy
    respond_with @present
  end

  private

  def present_params
    params.require(:present).permit(
      :contents, 
      :name_recepient, 
      :elf_id, 
      :status
      )
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  # override default kaminari pagination method to use twitter-bootstrap theme
  def paginate(objects, options={})
    options.reverse_merge!(theme: 'twitter-bootstrap-4',
                           pagination_class: 'pagination-sm')
    super(objects, options)
  end
end

app/views/dashboards/index.html.haml
.row
  .col.d-flex.align-items-center.justify-content-between
    %h1= "Dashboard"
.row
  .col.d-flex.align-items-center.justify-content-between
    %h2= "De Elven"

    
%table.table.table-striped
  %thead
    %tr
      %th= sort_link(@q, :first_name, Elf.human_attribute_name(:name))
      %th= sort_link(@q, :speciality, Elf.human_attribute_name(:speciality))
      %th= "Number of presents"
      %th= "Number of presents delivered"
      %th= "Number of presents to be delivered"
      %th= "Number of presents lost"
      %th{colspan: 3}

  %tbody
    - @elves.each do |elf|

      - delivered = 0
      - to_be_delivered = 0
      - lost = 0

      - elf.presents.each do |present|
        - if(present.status == "Delivered")
          - delivered += 1
      
        - if(present.status == "To be delivered")
          - to_be_delivered += 1
      
        - if(present.status == "Lost")
          - lost += 1
      
      
      %tr
        %td= elf.full_name
        %td= elf.speciality
        %td= elf.presents.count.to_i
        %td= delivered.to_i
        %td= to_be_delivered.to_i
        %td= lost.to_i

        

.pull-right
  = paginate @elves


.row
  .col.d-flex.align-items-center.justify-content-between
    %h2= "De Presents"

%table.table.table-striped
  %thead
    %tr
      %th= sort_link(@q, :contents, Present.human_attribute_name(:contents))
      %th= sort_link(@q, :name_recepient, Present.human_attribute_name(:name_recepient))
      %th= sort_link(@q, :elf_id, Present.human_attribute_name(:elf_id))
      %th= sort_link(@q, :status, Present.human_attribute_name(:status))
      %th{colspan: 3}

  %tbody
    - @presents.each do |present|
      %tr
        %td= present.contents
        %td= present.name_recepient
        %td= present.elf.first_name + " " + present.elf.last_name
        %td= present.status

        - if (present.status == 'Lost')
          %td.actions
            = link_to t('actions.resend'), new_present_path(present_contents: present.contents, present_name_recepient: present.name_recepient, present_elf_id: present.elf_id), class: 'btn btn-xs btn-dark'
        -else 
          %td
      
.row
  .col-sm-6
  .col-sm-6
    .pull-right
      = paginate @presents

app/views/elves/_form.html.haml
= bootstrap_form_for @elf, layout: :vertical do |f|
  .container
    = f.text_field :first_name
    = f.text_field :last_name
    = f.text_field :speciality
    = f.date_field :date_of_birth

    = f.primary

app/views/elves/edit.html.haml
= render 'form'

app/views/elves/index.html.haml
.row
  .col.d-flex.align-items-center.justify-content-between
    %h1= "#{@elves.count} #{Elf.model_name.human(count: @elves.count)}"
    = link_to t('actions.create'), new_elf_path, class: 'btn btn-primary'

%table.table
  %thead
    %tr
      %th= sort_link(@q, :first_name, Elf.human_attribute_name(:name))
      %th= sort_link(@q, :speciality, Elf.human_attribute_name(:speciality))
      %th= sort_link(@q, :created_at, Elf.human_attribute_name(:created_at))
      %th{colspan: 3}

  %tbody
    - @elves.each do |elf|
      %tr
        %td= elf.full_name
        %td= elf.speciality
        %td= elf.created_at.strftime('%e %B %Y')

        %td.actions
          = link_to t('actions.edit'), edit_elf_path(elf), class: 'btn btn-xs btn-light'
          = link_to t('actions.delete'), elf_path(elf), { method: :delete, class: 'btn btn-xs btn-warning', data: { confirm: t('actions.delete_question')}}

.pull-right
  = paginate @elves

app/views/elves/new.html.haml
= render 'form'

app/views/home/index.html.haml
%h1
  Merry Christmas! 🎅

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sping Admin
    /
      admin
      version: #{Rails.application.config.version} (#{l(Rails.application.config.version_time)})
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    /[if lt IE 9]
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.0.8/es5-shim.min.js"}
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"}
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"}
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"}
    = csrf_meta_tags
  %body{class: "#{controller.controller_name} #{@full_height_page ? 'full-height' : nil}"}
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      = link_to t('navbar.home'), root_path, class: 'navbar-brand'
      %button.navbar-toggler(data-target='#navbarNav' data-toggle='collapse' type='button')
        %span.navbar-toggler-icon

      .collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item{class: "#{'active' if is_active_link?(elves_path)}"}
            = link_to Elf.model_name.human(count: 2), elves_path, class: 'nav-link'
          %li.nav-item{class: "#{'active' if is_active_link?(presents_path)}"}
            = link_to Present.model_name.human(count: 2), presents_path, class: 'nav-link'
          %li.nav-item{class: "#{'active' if is_active_link?(dashboards_path)}"}
            = link_to Dashboard.model_name.human(count: 2), dashboards_path, class: 'nav-link'

    .main-content.container-fluid
      - flash.each do |type, msg|
        %div{class: "alert alert-#{type == 'alert' ? 'danger' : 'success'} alert-dismissable", role: 'alert'}
          %button.close{type: 'button', data: {dismiss: 'alert'}, aria: {label: 'Close'}}
            %span{aria: {hidden: 'true'}} &times;
          = msg if msg.is_a?(String)

      = yield

  = javascript_include_tag  'application'
  = javascript_pack_tag     'application'
  = yield :javascripts

app/views/presents/_form.html.haml
= bootstrap_form_for @present , layout: :vertical do |f|
  .container
    = f.text_field :contents, :value => params[:present_contents]
    = f.text_field :name_recepient, :value => params[:present_name_recepient]
    = f.text_field :elf_id, :value => params[:present_elf_id]
    = f.select :status, ['To be delivered', 'Delivered', 'Lost']


    = f.primary

app/views/presents/edit.html.haml
%h1= Present.model_name.human.singularize

= render 'form'

app/views/presents/index.html.haml
%h1= Present.model_name.human(count: 2)
.col.d-flex.align-items-center.justify-content-between
  %h1= "#{@presents.count} #{Present.model_name.human(count: @presents.count)}"
  %h1 Search
  = search_form_for @q do |f|
    .field
      =f.label :status_cont, "Status"
      =f.select :status_matches, options_for_select(['Delivered', 'To be delivered', 'Lost'])
      =f.submit "Filter"
  = link_to t('actions.create'), new_present_path, class: 'btn btn-primary'



%table.table.table-striped
  %thead
    %tr
      %th= sort_link(@q, :contents, Present.human_attribute_name(:contents))
      %th= sort_link(@q, :name_recepient, Present.human_attribute_name(:name_recepient))
      %th= sort_link(@q, :elf_id, Present.human_attribute_name(:elf_id))
      %th= sort_link(@q, :status, Present.human_attribute_name(:status))
      %th{colspan: 3}

  %tbody
    - @presents.each do |present|
      %tr
        %td= present.contents
        %td= present.name_recepient
        %td= present.elf.first_name + " " + present.elf.last_name
        %td= present.status

        - if (present.status != 'Lost')
          %td.actions
            = link_to t('actions.edit'), edit_present_path(present), class: 'btn btn-xs btn-light'
            = link_to t('actions.delete'), present_path(present), { method: :delete, class: 'btn btn-xs btn-warning', data: { confirm: t('actions.delete_question')}}
        - else
          %td.actions
            = link_to t('actions.resend'), new_present_path(present_contents: present.contents, present_name_recepient: present.name_recepient, present_elf_id: present.elf_id), class: 'btn btn-xs btn-dark'
            = link_to t('actions.edit'), edit_present_path(present), class: 'btn btn-xs btn-light'
            = link_to t('actions.delete'), present_path(present), { method: :delete, class: 'btn btn-xs btn-warning', data: { confirm: t('actions.delete_question')}}


.row
  .col-sm-6
  .col-sm-6
    .pull-right
      = paginate @presents

app/views/presents/new.html.haml
= render 'form'

app/views/presents/show.html.haml
%h1= Present.model_name.human.singularize

%dl.dl-horizontal
  %dt= Present.human_attribute_name :contents
  %dd= @present.contents
%dl.dl-horizontal
  %dt= Present.human_attribute_name :name_recepient
  %dd= @present.name_recepient
%dl.dl-horizontal
  %dt= Present.human_attribute_name :elf_id
  %dd= @present.elf_id
%dl.dl-horizontal
  %dt= Present.human_attribute_name :status
  %dd= @present.status

- if can? :update, @present
  = link_to t('actions.edit'), edit_present_path(@present)
  \|
= link_to t('actions.back'), presents_path